Repository adammartin1ets/oxygen-cs-gr01-eq11, pull requests merged in 2023-07, with the labels that each got.

#3 App containerization through Docker.
  Dockerfile
  docker-compose.yml
  requirements.txt
  src/main.py
Labels: enhancement, tasks

#9 Pre commit git hook
  .github/workflows/Unit_Tests.yml
  .github/workflows/pylint.yml
Labels: priority : Medium, pull request

#11 Update test.py
  test/test.py
Labels: priority : High, tasks

#12 Pylint refactoring
  .github/workflows/CI.yml
  .github/workflows/Unit_Tests.yml
  .github/workflows/pylint.yml
  src/db_manager.py
  src/main.py
  test/test.py
Labels: refactoring, priority : High, tasks

#14 [Pull Request] Develop into main
  .env.example
  .github/workflows/CI.yml
  Dockerfile
  database/docker-compose.yml
  docker-compose.yml
  requirements.txt
  src/main.py
  test/test.py
Labels: help wanted, priority : High, pull request

#15 Added Dockerhub image to docker-compose.yml and added Doc to run and …
  Dockerfile
  README.md
  docker-compose.yml
Labels: bug, documentation
